### ISSUE TITLE
win

### ISSUE THREAD

**Issue by jimsss977** [AXeL-dev/Dindo-Bot#21] opened 2020-05-22 22:54 UTC
lu, je voulais savoir s'il y aura une version ou le bot sera compatible avec windows dans le futur ?

**Comment by AXeL-dev** [comment] 2020-05-23 02:13
I honestly don't use windows anymore or at least not daily, so if no volunteer shows up i don't think that i will spend time on the windows version for no valuable reason.

**Comment by jimsss977** [comment] 2020-05-23 23:00
I saw another of your interesting projects concerning pixus but I think it needs to be updated. It is the management part of dd that interests me.
I would like to speak in private if you have time
thanks

**Comment by AXeL-dev** [comment] 2020-05-23 23:52
Pixus doesn't have dd management, only Dindo does. Also, Pixus is pretty much old & i don't think that i will update it, mostly because i didn't code with C# & visual studio from a long time in addition that those technologies are less used right now.

Coding is just a hobby for me, especially on github. I even don't use those bots right now, + i'm enough busy working on other projects, so if i ever update them it would surely be on my free time or when i get motivated to.

Sorry if it was a bit long, If you wanna talk in private just contact me on my email.

Regards

**Comment by AXeL-dev** [comment] 2020-05-25 11:36
Duplicate of #1

**Closed by AXeL-dev** 2020-05-25 11:36 UTC
Labels: question
