### ISSUE TITLE
I want to use this bot on windows 10

### ISSUE THREAD

**Issue by diamondwings** [AXeL-dev/Dindo-Bot#12] opened 2019-11-27 13:43 UTC
Yo AXel , I'm a moroccan guy who is really passionate about dragodinde breeding , i want to use this bot for automatisation of the tasks of dragodinde breeding , if you find time please help me .

My regards

**Comment by AXeL-dev** [comment] 2019-11-27 18:41
Hey,

That was the main purpose of the bot the first time i wrote it, in fact dragodinde breeding was already working for old Dofus versions (2.48 & less) & that's why i called the bot Dindo (from Drago**dind**e). Anyway, the breeding part may work for some cases but it still need to be improved i guess.

**Questions**: What kind of programming skills do you have? also do you know that the bot is currently not compatible with windows? so the first thing to do is to handle/make a compatible windows version.

**Comment by diamondwings** [comment] 2019-11-28 13:06
I don't have any programming skills but i know some friends who can do this for me !

**Comment by AXeL-dev** [comment] 2019-11-28 19:35
> I don't have any programming skills but i know some friends who can do this for me !

Okay, just go ahead then, i'll accept any pull request :wink:

**Comment by AXeL-dev** [comment] 2019-12-27 23:07
Duplicate of #1

**Closed by AXeL-dev** 2019-12-27 23:07 UTC
Labels: enhancement, help wanted

**Comment by arquin18** [comment] 2021-06-10 16:40
Amigo quisiera migrar el bot a Windows 10 me podrías guiar hay unas librería que no funcionan en Windows 
Cualquiera ayuda es bien recibida gracias
